# Cab Rider Data Analysis

In [1]:
#### Mean speed of all the rides
#### Number of rides taken in february
#### Number of rides where tip was more then $50
#### Number of rides where rides where drop was JFK airport
#### Most frequesnt pick up day of the week
#### Most frequent pick up location code (top 3)


In [2]:
import numpy as np
taxi =np.genfromtxt('nyc_taxis.csv', delimiter=',' ,skip_header =True)
print(taxi)
print(taxi.shape)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]
(89560, 15)


## Mean speed of all the rides

In [3]:
speed = taxi[:, 7]/ (taxi[:, 8] / 3600)
print("speed of every car", speed)

mean_speed = speed.mean()
print(f"The mean speed is --> {mean_speed:.3f}")

speed of every car [37.11340206 38.58157895 31.27222982 ... 22.29907867 42.41551247
 36.90473407]
The mean speed is --> 32.243


## Number of rides taken in february

In [4]:
# lets get pick up month column first
month = taxi[:, 1].astype('int8')
print(month)

# let find most occured month by find unique and its count
unique_values , count = np.unique(month, return_counts =True)
print(unique_values)
print(count)

max_occured_month = max(count)
print("Count of max occured month", max_occured_month)

print("argmax", np.argmax(count))
print("max", np.max(count))

# month_number = unique_values[count == max_occured_month]
month_number = unique_values[np.argmax(count)]  # Get the unique month with the maximum count
feb_rides = count[1]
print("Month were maximum rides where taken", month_number)
print("Number of rides taken in februray", feb_rides)




[1 1 1 ... 6 6 6]
[1 2 3 4 5 6]
[13481 13333 15547 14810 16650 15739]
Count of max occured month 16650
argmax 4
max 16650
Month were maximum rides where taken 5
Number of rides taken in februray 13333


## Number of rides where tip was more then $50

In [10]:
# Assuming tips is already extracted
tips = taxi[:, 12]
print("Tips column:", tips)

# Get indices where tips are greater than 50
greater_than_fifty_indices = np.where(tips > 50)
print("Indices where tips > 50:", greater_than_fifty_indices)

# Get the actual tips values corresponding to these indices
greater_than_fifty_values = tips[greater_than_fifty_indices]
print("Tip values greater than 50:", greater_than_fifty_values)

total = greater_than_fifty_values.shape[0]
print("Toal Rides where Tip value was greater than 50:", total)

Tips column: [11.65  8.    0.   ...  5.    8.95  0.  ]
Indices where tips > 50: (array([    5,  4297, 11711, 21710, 30961, 34929, 40974, 56485, 65532,
       69438, 76157, 76409, 77228, 77312, 84142, 85732]),)
Tip values greater than 50: [ 52.8   60.    59.34  80.    70.    60.    55.    65.    80.    62.
 100.    58.    62.    75.7   60.    70.  ]
Toal Rides where Tip value was greater than 50: 16


## Number of rides where rides where drop was JFK airport

In [37]:
drop_off = taxi[:, 6]
print(drop_off)

unique_values , count = np.unique(drop_off, return_counts=True)

print("The unique values of drop_off", unique_values)
print("The unique values of drop_off", count)

max_drop_off = unique_values[np.argmax(count)]
print("Maximum drop off took this year were", max_drop_off)

code = 2
jfk_drop = count[code]
print("Number of rides where rides where drop was JFK airport", jfk_drop)



[4. 1. 6. ... 4. 6. 0.]
The unique values of drop_off [0. 1. 2. 3. 4. 5. 6. 7.]
The unique values of drop_off [ 1043  9815 11832 16602 41130    63  9000    75]
Maximum drop off took this year were 4.0
Number of rides where rides where drop was JFK airport 11832


## Most frequesnt pick up day of the week

In [24]:
pick_up_day = taxi[:, 2]
print(pick_up_day)

unique_values , count = np.unique(pick_up_day, return_counts=True)

print("The unique values of pick_up_day", unique_values)
print("The unique values of pick_up_day", count)


max_drop_off = unique_values[np.argmax(count)]
print("Most frequesnt pick up day of the week", max_drop_off.astype('int8'))


[ 1.  1.  1. ... 30. 30. 30.]
The unique values of pick_up_day [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]
The unique values of pick_up_day [2953 2743 2921 2968 2841 2867 2855 3027 2815 3055 2955 2934 3009 2867
 3375 3100 3142 3168 3086 2979 2867 3100 2473 2701 3166 2947 2942 2964
 2956 2235 1549]
Most frequesnt pick up day of the week 15


## Most frequent pick up location code (top 3)

In [35]:
pick_code = taxi[:, 5]
print(pick_code)


unique_values , count = np.unique(pick_code, return_counts=True)

print("The unique values of pick_code", unique_values)
print("The unique values of pick_code", count)

# Sort unique values by counts in descending order
sorted_indices = np.argsort(-count)  # Negative for descending order
top_3_indices = sorted_indices[:3]  # Get indices of the top 3

print(sorted_indices)

top_3_codes = unique_values[top_3_indices]

print("Most frequent pick up location code (top 3)", top_3_codes.astype('int8'))

[2. 2. 2. ... 2. 2. 2.]
The unique values of pick_code [0. 1. 2. 3. 4. 6.]
The unique values of pick_code [   14   418 29329 34223 25057   519]
[3 2 4 5 1 0]
Most frequent pick up location code (top 3) [3 2 4]
